const fs = require('fs');
const path = require('path');

const BASE = 'C:\\Users\\Craig\\Downloads\\Charlie Chat\\assets\\symbols\\1. Main Boards\\Small Words';
const ICONS = {
    'abstract noun': 'abstract noun [montessori].png',
    'adjective': 'adjective [montessori].png',
    'adverb': 'adverb [montessori].png',
    'article': 'article [montessori].png',
    'auxiliary verb': 'auxiliary verb [montessori].png',
    'collective noun': 'collective noun [montessori].png',
    'conjunction': 'conjunction [montessori].png',
    'gerund': 'gerund (noun + ing) [montessori].png',
    'interjection': 'interjection [montessori].png',
    'intransitive verb': 'intransitive verb [montessori].png',
    'linking verb': 'linking verb [montessori].png',
    'noun': 'noun [montessori].png',
    'participle': 'participle (end in -ing, -ed, -en, -d, -t, -n, or -ne) [montessori].png',
    'preposition': 'preposition [montessori].png',
    'pronoun': 'pronoun [montessori].png',
    'proper noun': 'proper noun [montessori].png',
    'transitive verb': 'transitive verb [montessori].png',
    'other': 'other.png'
};

// Title Case folder names
const FOLDER_NAMES = {
    'abstract noun': 'Abstract Noun',
    'adjective': 'Adjective',
    'adverb': 'Adverb',
    'article': 'Article',
    'auxiliary verb': 'Auxiliary Verb',
    'collective noun': 'Collective Noun',
    'conjunction': 'Conjunction',
    'gerund': 'Gerund',
    'interjection': 'Interjection',
    'intransitive verb': 'Intransitive Verb',
    'linking verb': 'Linking Verb',
    'noun': 'Noun',
    'participle': 'Participle',
    'preposition': 'Preposition',
    'pronoun': 'Pronoun',
    'proper noun': 'Proper Noun',
    'transitive verb': 'Transitive Verb',
    'other': 'Other'
};

const WORDS = {
    'abstract noun': [
        'ability','absence','academy','account','act','action','activity','adventure','advice','age',
        'agreement','aim','alarm','anger','angle','answer','anxiety','apology','appearance','application',
        'appointment','approval','area','argument','army','art','attention','audience','authority','balance',
        'beauty','belief','birth','blame','blood','body','bonus','border','brain','bravery',
        'breath','brotherhood','business','calm','capacity','capital','captain','cause','celebration','centre',
        'chance','change','chaos','charm','childhood','choice','church','circle','citizen','climate',
        'comfort','command','comment','committee','communication','community','company','competition','concern','confidence',
        'conflict','conscience','consequence','contact','content','context','contract','contribution','control','conversation',
        'cooperation','courage','course','court','crisis','custom','damage','danger','data','deadline',
        'deal','death','debate','debt','decision','defeat','defence','degree','demand','democracy',
        'department','depression','description','desire','destination','destruction','detail','determination','development','difficulty',
        'direction','disadvantage','disaster','discussion','disease','distance','distraction','district','doctrine','doubt',
        'dream','duty','economy','education','effect','efficiency','effort','election','emotion','empire',
        'emphasis','employment','enemy','energy','engine','enthusiasm','environment','equipment','error','escape',
        'estate','ethics','evidence','evil','evolution','examination','example','exchange','excitement','exercise',
        'existence','expansion','experience','experiment','expert','explanation','exploration','expression','extent','extreme',
        'failure','faith','fame','family','fashion','fate','fear','fiction','field','fight',
        'figure','finance','finding','firm','flag','flame','flight','focus','force','freedom',
        'funeral','future','gain','gallery','gap','garden','gate','generation','genius','gift',
        'glory','goal','govern','grace','grade','grain','grammar','grief','guilt','habit',
        'hall','happiness','harmony','harvest','health','height','help','hero','history','holiday',
        'honour','hope','horror','hour','humour','hunger','hunt','hypothesis','identity','ignorance',
        'illness','illusion','imagination','importance','impression','improvement','incident','income','increase','independence',
        'industry','influence','information','injury','injustice','innocence','inquiry','insight','inspection','inspiration',
        'instance','institution','instruction','insurance','intellect','intention','interest','interpretation','intervention','introduction',
        'invasion','invention','investment','irony','judgement','justice','kingdom','knowledge','labour','landscape',
        'language','law','leadership','league','legend','leisure','length','lesson','liberty','license',
        'life','limit','link','literature','location','loss','love','luck','luxury','magic',
        'majority','management','manner','mansion','margin','mass','material','mathematics','matter','meaning',
        'measure','mechanism','media','medicine','memory','mercy','mess','method','military','mind',
        'ministry','minority','miracle','mission','mistake','modesty','moment','mood','mystery','myth',
        'nature','necessity','nerve','network','news','nightmare','nonsense','notion','number','object',
        'objection','obligation','observation','obstacle','occasion','offence','offer','office','operation','opinion',
        'opposition','opportunity','order','organisation','origin','outcome','output','owner','pain','pair',
        'pale','panic','paragraph','parliament','participation','partner','passage','passion','patience','peace',
        'penalty','pension','percentage','perception','period','permission','personality','perspective','phrase','pile',
        'pilot','pitch','place','plan','platform','pleasure','plot','pocket','poetry','policy',
        'politics','pollution','population','position','possibility','post','pound','poverty','power','practice',
        'praise','prayer','prediction','preference','preparation','presence','presentation','president','pressure','pride',
        'prince','principle','print','priority','prison','privacy','prize','problem','process','production',
        'profession','profit','progress','promise','property','proportion','proposal','prospect','protection','protest',
        'province','public','punishment','purchase','purpose','quality','quantity','quarter','queen','race',
        'radiation','rage','rail','rank','rate','ratio','reaction','reading','reality','reason',
        'rebellion','receipt','reception','record','recovery','reduction','reference','reflection','reform','refusal',
        'region','regret','relation','release','religion','remains','removal','rent','repair','repeat',
        'replacement','report','republic','reputation','request','requirement','research','reserve','resolution','resource',
        'respect','response','rest','result','retirement','return','reunion','revenue','review','revision',
        'revolution','reward','rhythm','risk','ritual','rival','role','row','rule','sacrifice',
        'safety','salary','sample','satisfaction','scale','scene','schedule','scheme','school','science',
        'scope','score','screen','sculpture','search','season','seat','section','security','selection',
        'sentence','series','settlement','shadow','shame','shape','share','shelter','shift','shock',
        'signal','silence','skill','slave','sleep','slope','society','soldier','solution','soul',
        'spirit','spite','sport','spot','spread','spring','square','stability','staff','stage',
        'standard','state','statement','station','status','stealth','steam','steel','stem','step',
        'stereotype','stimulus','stock','stomach','storm','story','strategy','strength','stress','structure',
        'struggle','substance','success','suffering','suggestion','summary','support','surface','surgeon','surplus',
        'surprise','survival','suspicion','symbol','sympathy','symptom','system','tale','talent','target',
        'task','taste','tax','teaching','team','technology','temperature','tension','terror','test',
        'testimony','text','theme','theory','thought','thunder','tide','title','tone','topic',
        'tradition','traffic','tragedy','training','transfer','treasure','treaty','trial','tribe','trick',
        'trip','trouble','trust','truth','turn','unemployment','union','unit','value','variety',
        'vehicle','version','victim','victory','violence','virtue','vision','volume','wage','waste',
        'wealth','weapon','weight','welfare','wheat','width','wildlife','wine','wing','wit',
        'wonder','work','worth','yard','yield','youth','zone'
    ],
    'adjective': [
        'able','absolute','accurate','actual','acute','additional','adequate','advanced','afraid','aggressive',
        'ancient','annual','anxious','apparent','appropriate','automatic','aware','awful','basic','beautiful',
        'big','bitter','blind','bold','brave','brief','bright','broad','broken','calm',
        'capable','careful','central','certain','cheap','chemical','chief','civil','clean','clear',
        'clever','clinical','close','cold','commercial','common','competitive','complex','compulsory','conscious',
        'considerable','constant','contemporary','content','continuous','conventional','correct','creative','critical','cruel',
        'cultural','current','daily','deaf','decent','deep','delicate','deliberate','delicious','different',
        'difficult','digital','direct','distinct','domestic','double','dry','dull','dutch','eager',
        'early','eastern','economic','educational','effective','efficient','elderly','electric','electronic','elegant',
        'empty','enormous','entire','environmental','equal','essential','ethnic','european','evident','exact',
        'excellent','exciting','existing','expensive','experimental','expert','external','extra','extraordinary','extreme',
        'familiar','famous','fantastic','fashionable','fast','fat','federal','female','fierce','final',
        'financial','fine','firm','fixed','flat','flexible','fluent','following','foolish','formal',
        'former','fortunate','frequent','fresh','friendly','frightened','front','full','funny','further',
        'future','general','genetic','genuine','giant','glad','global','good','gorgeous','grand',
        'grateful','great','green','grey','guilty','handsome','happy','hard','harsh','healthy',
        'heavy','helpful','hidden','high','hollow','holy','homeless','honest','hopeful','horrible',
        'hot','huge','human','humble','hungry','ideal','illegal','immediate','imperial','important',
        'impossible','impressive','incredible','independent','individual','industrial','informal','initial','inner','innocent',
        'instant','intellectual','intelligent','intense','internal','international','invisible','keen','large','latest',
        'lazy','legal','legitimate','likely','little','living','logical','lonely','loose','lovely',
        'low','lucky','mad','magic','main','major','male','massive','mature','maximum',
        'mean','medical','mental','mere','middle','mild','military','minimum','minor','mobile',
        'modern','moral','multiple','mutual','narrow','nasty','national','native','natural','nearby',
        'necessary','negative','nervous','neutral','new','nice','noble','normal','northern','nuclear',
        'numerous','obvious','odd','official','old','online','open','opposite','ordinary','organic',
        'original','other','outer','outside','overall','painful','pale','particular','past','patient',
        'peaceful','perfect','permanent','personal','physical','plain','pleasant','pleased','political','poor',
        'popular','positive','possible','potential','powerful','practical','precious','pregnant','previous','primary',
        'private','professional','proper','proud','public','pure','purple','quick','quiet','racial',
        'radical','random','rapid','rare','raw','ready','real','reasonable','recent','red',
        'regional','regular','related','relative','relevant','religious','reluctant','remarkable','remote','responsible',
        'revolutionary','rich','rising','rough','round','royal','rural','sad','safe','satisfying',
        'scared','scary','secondary','secret','secure','select','sensitive','separate','serious','severe',
        'shallow','sharp','sheer','short','shy','sick','significant','silly','similar','simple',
        'single','slight','slow','small','smart','smooth','soft','solid','southern','spare',
        'special','specific','spiritual','stable','standard','strange','strict','strong','substantial','successful',
        'sudden','suffering','suitable','superior','supreme','sure','surprising','sweet','tall','temporary',
        'terrible','thick','thin','thorough','tight','tiny','tired','total','tough','traditional',
        'tremendous','tropical','typical','ugly','ultimate','unable','uncertain','underground','unfair','unfortunate',
        'unhappy','unique','unlikely','unnecessary','unpleasant','upper','urban','useful','usual','valuable',
        'various','vast','violent','virtual','visible','visual','vital','vivid','vocal','voluntary',
        'vulnerable','warm','weak','weird','western','wet','white','whole','wide','wild',
        'willing','wise','wonderful','wooden','worthy','young'
    ],
    'adverb': [
        'absolutely','accidentally','accordingly','accurately','actively','actually','additionally','adequately','apparently','approximately',
        'automatically','barely','basically','briefly','broadly','carefully','certainly','clearly','closely','commonly',
        'completely','constantly','continually','continuously','currently','daily','deeply','directly','doubtfully','dramatically',
        'effectively','efficiently','entirely','especially','essentially','eventually','evidently','exactly','exclusively','extremely',
        'fairly','finally','firmly','formally','formerly','fortunately','frequently','fully','generally','gently',
        'gradually','greatly','happily','hardly','heavily','honestly','hopefully','however','immediately','importantly',
        'incorrectly','indeed','independently','initially','instantly','instead','largely','lately','literally','mainly',
        'merely','moreover','mostly','naturally','nearly','necessarily','nevertheless','normally','notably','obviously',
        'occasionally','officially','only','openly','otherwise','partially','particularly','perfectly','permanently','personally',
        'physically','politely','possibly','potentially','practically','precisely','previously','primarily','privately','probably',
        'properly','purely','rapidly','rarely','readily','really','recently','regularly','relatively','remarkably',
        'repeatedly','roughly','sadly','safely','seriously','sharply','shortly','significantly','silently','simply',
        'slightly','slowly','smoothly','solely','specifically','steadily','strictly','strongly','successfully','suddenly',
        'sufficiently','surely','temporarily','thoroughly','tight','tightly','today','together','tomorrow','tonight',
        'totally','traditionally','truly','typically','ultimately','undoubtedly','unfortunately','unusually','urgently','usually',
        'vaguely','virtually','widely','yesterday'
    ],
    'article': ['a','an','the'],
    'auxiliary verb': [
        'am','is','are','was','were','be','been','being',
        'have','has','had','having','do','does','did','doing',
        'shall','should','will','would','may','might','must',
        'can','could','need','ought','dare','used'
    ],
    'collective noun': [
        'academy','act','agency','army','assembly','band','bank','board','body','brigade',
        'brood','bunch','cabinet','cage','caravan','chain','choir','chorus','circle','class',
        'club','cluster','collection','colony','commission','committee','community','company','congregation','congress',
        'corps','corporation','council','couple','court','crew','crowd','division','faculty','family',
        'flock','force','gang','galaxy','generation','government','group','guard','guild','herd',
        'horde','host','huddle','jury','knot','litter','lot','mass','mob','multitude',
        'nest','network','pack','panel','parliament','patrol','peal','people','pile','platoon',
        'posse','pride','procession','program','public','range','rank','regiment','series','set',
        'shoal','skeleton','staff','swarm','team','throng','tribe','troupe','unit','watch',
        'batch','bevy','bench','bouquet','budget'
    ],
    'conjunction': [
        'although','and','as','because','before','but','by','either','however','if',
        'lest','neither','nor','once','or','provided','since','so','so that','still',
        'than','that','though','till','until','when','whenever','where','whereas','wherever',
        'whether','while','yet'
    ],
    'gerund': [
        'acting','adding','admitting','advising','agreeing','allowing','answering','apologizing','appearing','applying',
        'approving','arguing','arranging','asking','avoiding','baking','balancing','bargaining','bathing','beginning',
        'behaving','believing','belonging','bending','betting','binding','biting','bleeding','blending','blessing',
        'blocking','blowing','boasting','borrowing','bouncing','breaking','breathing','breeding','bringing','broadcasting',
        'bubbling','building','burning','bursting','buying','calculating','calling','caring','carrying','catching',
        'causing','celebrating','challenging','changing','charging','chasing','checking','cheering','chewing','choosing',
        'claiming','clapping','cleaning','clearing','climbing','closing','coaching','collecting','combining','comforting',
        'commanding','communicating','comparing','competing','complaining','completing','concentrating','connecting','considering','consulting',
        'containing','continuing','controlling','converting','convincing','cooking','copying','correcting','counting','creating',
        'crossing','crying','cutting','dancing','dealing','deciding','declaring','decreasing','defending','delivering',
        'demonstrating','denying','depending','describing','designing','destroying','developing','digging','directing','disappearing',
        'discovering','discussing','distributing','dividing','doubting','drawing','dreaming','dropping','drying','earning',
        'eating','educating','emphasizing','enabling','encouraging','enjoying','entering','entertaining','examining','exchanging',
        'exciting','excusing','exercising','existing','expecting','experiencing','explaining','exploring','expressing','extending',
        'facing','falling','farming','fearing','feeding','feeling','fetching','fighting','filling','finding',
        'finishing','fixing','floating','flowing','flying','following','forbidding','forcing','forgetting','forgiving',
        'forming','getting','giving','going','governing','grasping','greeting','growing','guarding','guiding',
        'handling','hanging','happening','harming','hating','healing','hearing','helping','hesitating','hiding',
        'hitting','hoping','hunting','hurting','imagining','including','increasing','influencing','informing','instructing',
        'intending','introducing','inventing','inviting','joining','joking','judging','jumping','keeping','kicking',
        'killing','kissing','kneeling','knocking','knowing','landing','laughing','laying','leading','learning',
        'leaving','lending','letting','lifting','lighting','liking','limiting','listing','listening','living',
        'looking','losing','loving','making','managing','marching','marking','matching','measuring','meeting',
        'mentioning','messaging','minding','missing','mixing','moving','multiplying','naming','needing','noticing',
        'obeying','observing','obtaining','offering','operating','ordering','organizing','owning','painting','participating',
        'passing','paying','performing','permitting','persuading','picking','placing','planting','playing','pleasing',
        'pointing','polishing','pouring','practicing','praising','praying','predicting','preparing','presenting','pressing',
        'preventing','producing','protecting','providing','publishing','pulling','pumping','punishing','purchasing','pushing',
        'putting','questioning','racing','raising','reaching','reading','receiving','recognizing','recommending','recording',
        'recovering','reducing','reflecting','refusing','relating','relaxing','releasing','removing','renting','repairing',
        'repeating','replacing','reporting','representing','requesting','requiring','rescuing','researching','resisting','respecting',
        'resting','restoring','restricting','retiring','returning','reversing','riding','ringing','rising','risking',
        'robbing','rolling','running','rushing','satisfying','saving','saying','scaring','scattering','seeking',
        'selecting','selling','sending','separating','serving','setting','settling','shaking','sharing','shining',
        'shooting','shopping','shouting','showing','shutting','signing','singing','sitting','sleeping','smelling',
        'smiling','solving','sorting','speaking','speeding','spending','spinning','splitting','spreading','squeezing',
        'standing','starting','stating','staying','stealing','steering','sticking','stirring','stopping','storing',
        'stretching','striking','struggling','studying','succeeding','suffering','suggesting','supplying','supporting','supposing',
        'surfing','surrounding','surviving','suspecting','swallowing','swapping','swearing','sweeping','swimming','swinging',
        'taking','talking','tasting','teaching','tearing','telling','thinking','threatening','throwing','touching',
        'training','translating','travelling','treating','tricking','trying','turning','typing','understanding','unifying',
        'uniting','using','valuing','visiting','waiting','walking','wanting','warming','warning','washing',
        'watching','waving','weaving','weighing','welcoming','whispering','winning','wishing','wondering','working',
        'worrying','wrapping','writing','yielding'
    ],
    'interjection': [
        'ah','ahem','alas','amen','argh','aw','aww','bah','blah','bravo',
        'bye','cheers','congratulations','dang','darn','doh','duh','eek','eh','eureka',
        'gee','golly','goodbye','gosh','ha','hallelujah','hello','hey','hi','hm',
        'hmm','ho','hooray','huh','hurray','jeez','lo','man','meh','mmm',
        'hmph','nah','no','oh','ooh','oops','ouch','ow','phew','phooey',
        'pooh','shh','shoo','sigh','ta','ta-da','tch','thanks','there','tisk',
        'tsk','ugh','voila','wahoo','well','what','whew','whoa','whoopee','wow',
        'yay','yes','yo','yikes','yippee','yoohoo','zap'
    ],
    'intransitive verb': [
        'ache','adapt','adhere','adjust','agree','appear','apply','arrive','assert','assist',
        'attend','belong','boil','bounce','breathe','burn','burst','cease','collapse','come',
        'consist','continue','contribute','correspond','cough','crash','creep','cry','dance','depend',
        'die','disappear','differ','dig','disagree','doze','dream','drip','drown','exist',
        'fade','fall','float','flow','fly','freeze','gasp','gel','go','grow',
        'happen','heal','hibernate','hiss','hop','hurry','itch','jog','jump','kneel',
        'knock','land','laugh','leak','leap','lie','listen','live','look','matter',
        'melt','multiply','nap','occur','overflow','pause','persist','play','pour','pray',
        'protest','rain','react','rely','remain','respond','rest','rise','rot','rush',
        'scream','shine','shiver','shrink','sing','sit','sleep','slip','sneeze','snore',
        'soak','sparkle','speak','spin','splash','spread','spring','stagger','stand','stare',
        'stay','stink','stumble','succeed','suffer','swim','swing','thrive','travel','tremble',
        'trip','vanish','vibrate','wait','walk','wander','wince','wink','wither','wonder',
        'work','worry','yawn'
    ],
    'linking verb': [
        'am','appear','are','be','become','been','being','feel','get','grow',
        'is','look','prove','remain','seem','smell','sound','stay','taste','turn',
        'was','were'
    ],
    'noun': [
        'ability','accident','account','act','action','activity','address','advantage','adventure','advice',
        'age','agency','agreement','air','amount','anger','angle','animal','answer','anxiety',
        'apartment','appearance','apple','application','appointment','area','argument','arm','army','art',
        'article','artist','attack','attempt','attention','audience','author','autumn','baby','back',
        'background','bag','balance','ball','bank','bar','base','baseball','basket','bat',
        'bath','battle','beach','bear','beauty','bed','bedroom','beginning','behavior','belief',
        'bell','belt','bird','birth','bit','block','blood','blow','board','boat',
        'body','bone','book','border','boss','bottom','box','boy','brain','branch',
        'brand','bread','break','breakfast','breath','bridge','brother','budget','building','bus',
        'business','butter','button','cabinet','cake','call','camera','camp','campaign','capital',
        'car','card','care','career','carpet','case','cash','cat','cause','cell',
        'center','century','chair','champion','chance','change','channel','chapter','character','charge',
        'cheese','chest','chicken','child','choice','church','circle','city','claim','class',
        'classroom','clerk','client','clock','club','coach','coast','coat','code','coffee',
        'collection','college','color','column','combination','comfort','command','comment','commission','committee',
        'company','competition','computer','concern','condition','conference','confidence','conflict','connection','consequence',
        'construction','contact','content','context','contract','contribution','control','conversation','cooperation','corner',
        'cost','council','count','country','couple','courage','course','court','cover','craft',
        'crash','cream','creation','credit','crew','crisis','criticism','cross','crowd','cry',
        'culture','cup','current','customer','cycle','damage','dance','danger','data','date',
        'daughter','day','deal','death','debate','debt','decision','deck','defence','degree',
        'delivery','demand','department','depression','depth','description','desert','design','desk','detail',
        'development','device','diamond','diet','difficulty','dinner','direction','director','discipline','discussion',
        'disease','distance','doctor','dog','dollar','door','double','doubt','draft','drama',
        'dream','dress','drink','drive','driver','drop','drug','dust','duty','earth',
        'economy','edge','editor','education','effect','efficiency','effort','egg','election','element',
        'emergency','emotion','emphasis','employee','end','enemy','energy','engine','entertainment','enthusiasm',
        'entrance','entry','environment','equipment','error','escape','estate','evening','evidence','exchange',
        'exercise','experience','experiment','expert','explanation','expression','extent','eye','face','facility',
        'fact','factor','failure','faith','family','fan','farm','farmer','fashion','father',
        'fault','fear','feature','fee','feeling','field','fight','figure','file','film',
        'final','finger','fire','firm','fish','flag','flight','floor','flow','flower',
        'fly','food','foot','football','force','forest','form','fortune','foundation','frame',
        'freedom','friend','front','fruit','fuel','fun','function','future','gain','game',
        'garage','garden','gas','gate','gathering','generation','gift','girl','glass','glove',
        'goal','god','gold','golf','good','government','grade','grain','grammar','grandfather',
        'grandmother','grass','grip','group','growth','guard','guest','guide','guitar','guy',
        'habit','hall','hand','handle','hanger','happiness','harbor','hat','head','health',
        'heat','height','help','hero','highway','hill','history','hole','holiday','home',
        'honor','hook','hope','horror','horse','hospital','host','hotel','hour','house',
        'humor','hunt','hunting','hurry','husband','ice','idea','identity','illness','image',
        'imagination','impact','importance','impression','improvement','incident','income','increase','independence','index',
        'industry','inflation','influence','information','injury','innocence','input','inquiry','inspection','instance',
        'institution','instruction','instrument','insurance','intelligence','intention','interest','interpretation','intervention','introduction',
        'investment','iron','island','issue','item','jacket','jail','jar','jaw','jazz',
        'jeans','jewel','job','join','joke','journal','journey','joy','judge','judgment',
        'juice','jump','justice','key','kid','kill','king','kiss','kitchen','knee',
        'knife','knock','knowledge','lack','lady','lake','land','landscape','language','laugh',
        'law','lawyer','layer','lead','leader','league','learning','leather','leave','lecture',
        'leg','length','lesson','letter','level','liberty','library','license','lie','life',
        'lift','light','limit','line','link','lip','list','literature','location','lock',
        'log','love','luck','lunch','machine','magazine','mail','majority','management','manager',
        'manner','map','mark','market','marriage','mask','mass','master','match','material',
        'math','matter','meal','measure','meat','mechanism','media','medicine','meeting','member',
        'memory','message','metal','method','middle','milk','mind','mine','minister','minority',
        'minute','mirror','miss','mission','mistake','mix','model','moment','monitor','mood',
        'moon','morning','mortgage','mother','motion','motor','mountain','mouse','mouth','movement',
        'movie','mud','murder','muscle','museum','music','mystery','nail','name','nation',
        'nature','navy','neck','need','nerve','network','news','newspaper','night','noise',
        'north','note','nothing','notice','novel','number','nurse','object','objection','obligation',
        'observation','obstacle','occasion','offence','offer','office','officer','oil','opinion','opposition',
        'option','orange','order','organization','origin','output','owner','pace','pack','package',
        'page','pain','pair','palace','palm','panel','panic','paper','paragraph','parent',
        'park','partner','party','passage','passenger','passion','past','path','patience','pattern',
        'payment','peace','pen','pension','percent','performance','period','permission','person','personality',
        'perspective','phone','photo','phrase','piano','picture','piece','pig','pile','pilot',
        'pin','pitch','place','plan','platform','player','please','pleasure','plot','pocket',
        'poem','poet','poetry','point','pole','police','policy','politics','pollution','pool',
        'popularity','population','position','possession','possibility','post','pound','poverty','power','practice',
        'praise','prayer','prediction','preference','preparation','presence','presentation','president','pressure','pride',
        'prince','princess','principle','print','priority','prison','privacy','prize','problem','process',
        'production','profession','profit','progress','promise','property','proportion','proposal','prospect','protection',
        'protest','province','public','punishment','purchase','purpose','queen','question','race','radiation',
        'rage','rail','rank','rate','ratio','reaction','reading','reality','reason','rebellion',
        'receipt','reception','record','recovery','reduction','reference','reflection','reform','refusal','region',
        'regret','relation','release','religion','remains','removal','rent','repair','repeat','replacement',
        'report','republic','reputation','request','requirement','research','reserve','resolution','resource','respect',
        'response','rest','result','retirement','return','reunion','revenue','review','revision','revolution',
        'reward','rhythm','risk','ritual','rival','role','row','rule','sacrifice','safety',
        'salary','sample','satisfaction','scale','scene','schedule','scheme','school','science','scope',
        'score','screen','sculpture','search','season','seat','section','security','selection','sentence',
        'series','settlement','shadow','shame','shape','share','shelter','shift','shock','signal',
        'silence','skill','slave','sleep','slope','society','soldier','solution','soul','spirit',
        'spite','sport','spot','spread','spring','square','stability','staff','stage','standard',
        'state','statement','station','status','stealth','steam','steel','stem','step','stereotype',
        'stimulus','stock','stomach','storm','story','strategy','strength','stress','structure','struggle',
        'substance','success','suffering','suggestion','summary','support','surface','surgeon','surplus','surprise',
        'survival','suspicion','symbol','sympathy','symptom','system','tale','talent','target','task',
        'taste','tax','teaching','team','technology','temperature','tension','terror','test','testimony',
        'text','theme','theory','thought','thunder','tide','title','tone','topic','tradition',
        'traffic','tragedy','training','transfer','treasure','treaty','trial','tribe','trick','trip',
        'trouble','trust','truth','turn','unemployment','union','unit','value','variety','vehicle',
        'version','victim','victory','violence','virtue','vision','volume','wage','waste','wealth',
        'weapon','weight','welfare','wheat','width','wildlife','wine','wing','wit','wonder',
        'work','worth','yard','yield','youth','zone'
    ],
    'participle': [
        'accepted','aching','acted','added','adjusted','advanced','aged','allowed','amazed','annoyed',
        'annoying','approved','attached','baked','balanced','based','bent','bitten','bleeding','blocked',
        'blown','boiled','bored','boring','born','broken','burned','burst','bought','called',
        'cancelled','capable','caught','challenged','changed','charged','chased','checked','cheered','chosen',
        'civilised','claimed','closed','combined','compared','completed','concerned','connected','considered','contained',
        'continued','controlled','convinced','cooked','copied','corrected','covered','created','crossed','crowded',
        'cut','damaged','dared','decided','declared','decreased','defeated','defined','delayed','delivered',
        'described','designed','destroyed','developed','devoted','digging','directed','discovered','discussed','divided',
        'done','doubted','drawn','dreamed','dressed','driven','dropped','drowned','drunk','dried',
        'earned','eaten','educated','embedded','encouraged','engaged','enjoyed','entertained','escaped','established',
        'eaten','excited','exciting','experienced','expected','explained','explored','expressed','extended','faced',
        'fallen','famous','fastened','fed','filled','fixed','flown','focused','forbidden','forced',
        'forgotten','formed','found','frightened','frozen','funded','given','gone','grabbed','grown',
        'guided','handled','hidden','hit','honored','hoped','hunted','hurt','identified','ignored',
        'imagined','impressed','improved','included','increased','influenced','injured','inspired','instructed','intended',
        'interested','interested','introduced','invited','involved','joined','judged','kept','kicked','killed',
        'known','labeled','lacking','landed','launched','layered','leaned','learned','left','lent',
        'limited','lined','linked','loaded','located','locked','lost','loved','managed','marked',
        'married','matched','measured','met','mixed','monitored','moved','named','needed','noticed',
        'obtained','offered','opened','operated','ordered','organized','owned','painted','participated','passed',
        'patched','patient','paused','performed','persuaded','picked','placed','planned','planted','played',
        'pleased','pointed','polished','popped','positioned','posted','poured','powered','practiced','praised',
        'predicted','prepared','presented','pressed','prevented','produced','protected','proven','provided','published',
        'pulled','punished','purchased','pushed','put','puzzled','questioned','raced','raised','reached',
        'read','received','recognized','recommended','recorded','reduced','refused','related','relaxed','released',
        'removed','rented','repaired','repeated','replaced','reported','represented','requested','required','rescued',
        'researched','reserved','respected','rested','restored','restricted','retired','returned','revealed','reviewed',
        'rewarded','rid','risen','robbed','rocked','ruled','run','rushed','satisfied','saved',
        'scared','scattered','seated','secured','selected','separated','served','settled','shaken','shared',
        'shocked','shouted','shown','shut','sick','signified','silenced','simplified','slowed','solved',
        'sorted','split','spread','squeezed','stained','standardized','stared','started','stated','stayed',
        'stolen','stirred','stopped','stored','stretched','stripped','struck','stuck','studied','submitted',
        'suffered','suggested','supplied','supported','supposed','surprised','surrounded','survived','suspected','taken',
        'talked','tested','threatened','thrown','tied','tired','told','torn','touched','trained',
        'transferred','translated','treated','tricked','tried','troubled','trusted','turned','typed','unified',
        'united','unsettled','used','valued','visited','volunteered','waited','walked','warned','washed',
        'wasted','watched','watered','weighed','welcomed','whispered','widened','willed','won','wondered',
        'worked','worried','wrapped','written','wronged'
    ],
    'preposition': [
        'aboard','about','above','across','after','against','ahead','along','amid','among',
        'anti','around','as','at','behind','below','beneath','beside','besides','between',
        'beyond','but','by','concerning','considering','despite','down','during','except','excepting',
        'excluding','following','for','from','in','inside','into','like','mid','minus',
        'near','nearby','of','off','on','onto','opposite','out','outside','over',
        'past','per','plus','regarding','round','sans','since','than','through','throughout',
        'till','to','toward','towards','under','underneath','unlike','until','up','upon',
        'versus','via','with','within','without','worth'
    ],
    'pronoun': [
        'all','another','any','anybody','anyone','anything','both','each','either','everybody',
        'everyone','everything','few','he','her','hers','herself','him','himself','his',
        'i','it','its','itself','least','less','many','me','mine','more',
        'most','much','my','myself','neither','no','nobody','none','no one','nothing',
        'one','other','others','our','ours','ourselves','several','she','some','somebody',
        'someone','something','such','that','their','theirs','them','themselves','these','they',
        'this','those','us','what','whatever','which','whichever','who','whoever','whom',
        'whomever','whose','you','yours','yourself','yourselves'
    ],
    'proper noun': [
        'adam','africa','alice','america','amsterdam','andrew','angela','antarctica','arthur','asia',
        'athens','august','australia','barack','berlin','bible','bob','boston','britain','brussels',
        'buckingham','canada','capetown','carl','charles','chicago','china','christmas','churchill','circle',
        'claude','columbus','confucius','cook','daniel','david','december','denmark','diana','dublin',
        'edward','egypt','elizabeth','england','europe','february','florence','france','frank','friday',
        'franklin','french','george','germany','greece','greenland','harry','hawaii','henry','himalayas',
        'holland','hollywood','house','india','indonesia','iran','iraq','ireland','israel','italy',
        'jack','jacob','james','jane','january','japan','jefferson','jerusalem','jesus','jimmy',
        'joe','john','jonathan','joseph','joshua','julia','julius','june','justin','kenya',
        'kevin','kingston','korea','london','louis','louise','lucy','madrid','malcolm','manchester',
        'march','maria','marie','mark','martin','mary','matt','matthew','maya','michael',
        'michelle','monday','monica','montreal','moscow','munich','nancy','napoleon','nelson','nevada',
        'new','nicholas','nick','nigeria','nikki','november','oakland','october','oscar','oslo',
        'paris','paul','peter','philadelphia','philip','phoenix','plato','poland','portugal','prince',
        'queen','rachel','ramsay','rebecca','richard','robert','rome','ronald','rose','ross',
        'roy','russia','sam','samuel','saturday','scotland','september','shakespeare','sheffield','sophia',
        'stephen','steve','steven','sunday','susan','sydney','taiwan','texas','thailand','thomas',
        'titanic','tuesday','turkey','tuscany','tyler','uncle','uranus','venus','victoria','vincent',
        'virginia','wales','washington','wednesday','william','willy','winston','york'
    ],
    'transitive verb': [
        'accept','access','achieve','acknowledge','acquire','adapt','admit','adopt','advance','advise',
        'affect','afford','agree','alert','allow','announce','answer','apologise','appeal','appear',
        'apply','appoint','approach','approve','argue','arrange','arrest','arrive','assess','assign',
        'assist','assume','attach','attack','attend','attract','authorise','avoid','award','balance',
        'ban','bank','base','beat','believe','belong','bet','bite','blame','blend',
        'block','blow','boil','bomb','book','borrow','bottle','bounce','bowl','breathe',
        'broadcast','brush','build','burn','bury','buy','calculate','cancel','capture','care',
        'carry','catch','cause','celebrate','challenge','change','charge','chase','check','cheer',
        'chew','choose','claim','clap','classify','clean','clear','climb','clone','close',
        'coach','collect','combine','command','commit','communicate','compare','compete','complain','complete',
        'compose','concentrate','concern','conclude','conduct','confirm','confuse','connect','consider','consist',
        'construct','consult','contain','continue','contribute','control','convert','convince','cook','copy',
        'correct','count','cover','create','cross','crowd','cure','damage','dare','deal',
        'debate','decay','decide','declare','decorate','decrease','defeat','defend','define','delay',
        'deliver','demand','demonstrate','deny','depend','describe','deserve','design','destroy','detail',
        'detect','develop','devote','dig','direct','disappear','discover','discuss','dismiss','display',
        'distribute','divide','dominate','donate','double','doubt','download','drag','drain','draw',
        'dream','dress','drink','drive','drop','drown','dump','earn','eat','edit',
        'educate','elect','eliminate','embrace','employ','encourage','enjoy','enter','entertain','equip',
        'escape','establish','estimate','examine','exchange','exclude','excuse','exercise','exhibit','exist',
        'expand','expect','experience','experiment','explain','explode','export','expose','extend','face',
        'fail','fancy','feature','feed','fetch','fight','file','fill','film','find',
        'finish','fit','fix','float','fold','follow','forbid','force','forecast','forget',
        'forgive','found','freeze','frighten','gain','gather','give','glue','grab','graduate',
        'grant','grill','grind','guard','guess','hand','handle','hang','harm','hate',
        'have','heal','hear','heat','help','hide','hit','hold','hook','hope',
        'hunt','hurt','ignore','imagine','import','impress','improve','include','increase','indicate',
        'inform','injure','insert','inspect','install','instruct','insure','intend','introduce','invade',
        'invent','invest','invite','iron','isolate','judge','kick','kill','kiss','knead',
        'kneel','knit','knock','label','land','last','launch','lay','lead','lean',
        'leap','learn','leave','lend','let','lift','like','limit','link','listen',
        'load','locate','lock','love','make','manage','mark','marry','match','measure',
        'mention','merge','mind','miss','mix','monitor','name','need','notice','obey',
        'observe','obtain','occupy','offend','offer','operate','order','organise','overcome','owe',
        'own','paint','park','pass','patch','pause','pay','permit','persuade','pick',
        'plant','play','please','point','polish','pour','praise','predict','prefer','prepare',
        'present','preserve','press','pretend','prevent','print','produce','promise','promote','protect',
        'prove','provide','publish','pull','pump','punish','purchase','pursue','push','qualify',
        'quit','quote','raise','reach','read','realise','receive','recognise','recommend','record',
        'reduce','reflect','refuse','regard','regret','reject','relate','release','remember','remind',
        'remove','rent','repair','repeat','replace','reply','report','represent','request','require',
        'rescue','research','resist','respect','respond','restore','restrict','retain','retire','return',
        'review','ride','ring','rise','risk','rob','rock','rule','run','rush',
        'satisfy','save','scratch','search','seat','seek','seize','select','sell','send',
        'separate','serve','set','settle','shake','shape','share','shave','shift','shine',
        'shock','shoot','shout','show','shut','sign','signal','sing','sink','sit',
        'slap','sleep','slice','slide','slip','slow','smell','smile','smoke','snap',
        'solve','sort','sound','spell','spend','split','spot','spread','spy','squeeze',
        'stain','stamp','stand','start','state','stay','steal','stick','stir','stop',
        'store','stretch','strike','strip','struggle','study','submit','succeed','suffer','suggest',
        'supply','support','suppose','surprise','surround','survive','suspect','swallow','swear','sweep',
        'swim','switch','take','talk','tap','taste','teach','tear','tell','tend',
        'test','thank','think','throw','tie','tolerate','touch','tough','train','transfer',
        'translate','treat','trick','trust','try','turn','type','understand','unite','urge',
        'use','value','view','visit','vote','wage','wait','wake','walk','want',
        'warn','wash','waste','watch','wave','wear','weigh','welcome','whip','whisper',
        'wish','wonder','wrap','write','yield'
    ],
    'other': [
        'definitely','perhaps','maybe','although','therefore','however','moreover','furthermore','nevertheless','consequently',
        'meanwhile','otherwise','instead','likewise','similarly','conversely','nonetheless','hence','thus','accordingly',
        'besides','notwithstanding','albeit','whilst','lest','henceforth','hitherto','hereafter','thereafter','forthwith'
    ]
};

// Create text files and copy PNGs
let totalWords = 0;
let totalPngs = 0;

Object.entries(WORDS).forEach(([typeKey, words]) => {
    const folderName = FOLDER_NAMES[typeKey];
    const iconFile = ICONS[typeKey];
    const iconPath = path.join(BASE, iconFile);

    // Create text file
    const txtPath = path.join(BASE, folderName + '.txt');
    fs.writeFileSync(txtPath, words.join('\n'), 'utf8');
    console.log('Text: ' + folderName + '.txt (' + words.length + ' words)');
    totalWords += words.length;

    // Create folder
    const folderPath = path.join(BASE, folderName);
    fs.mkdirSync(folderPath, { recursive: true });

    // Copy PNG for each word
    if (fs.existsSync(iconPath)) {
        words.forEach(word => {
            const pngName = word.toLowerCase() + '.png';
            const destPath = path.join(folderPath, pngName);
            fs.copyFileSync(iconPath, destPath);
            totalPngs++;
        });
        console.log('PNGs: ' + folderName + '/ (' + words.length + ' files)');
    } else {
        console.log('WARNING: Icon not found: ' + iconFile);
    }
});

console.log('');
console.log('Done! Total: ' + totalWords + ' words, ' + totalPngs + ' PNGs created.');
