[build]
  command = "echo 'Using pre-built web folder from repository'"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200