// AUTO-GENERATED by tools/generate_symbol_data.py - do not edit manually.
// Scans assets/ for all .png files.

import '../models/symbol_tile.dart';

final List<String> allCategories = [];

final List<SymbolTile> allSymbolTiles = [];
