import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOARDS_DIR = ROOT / 'lib' / 'data' / 'boards'
HIERARCHY_BAK = ROOT / 'lib' / 'data' / 'board_hierarchy.dart'
HIERARCHY_OUT = ROOT / 'lib' / 'data' / 'board_hierarchy.dart'
INDEX_OUT = ROOT / 'lib' / 'data' / 'board_index.dart'
PUBSPEC = ROOT / 'pubspec.yaml'

LEGENDS_ORDER = [
    'Characters',
    'Creatures & Races',
    'Misc',
]
LEGENDS_ORDER_LOWER = {n.lower(): i for i, n in enumerate(LEGENDS_ORDER)}

def load(p):
    with open(p, 'r', encoding='utf-8') as f:
        return json.load(f)

def save(p, data):
    with open(p, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write('\n')

def board_id_in_dir(d):
    if not d.is_dir():
        return None
    for f in sorted(d.iterdir()):
        if f.is_file() and f.suffix == '.json':
            try:
                return load(f).get('id')
            except Exception:
                continue
    return None

def fix_all():
    for area_dir in sorted(BOARDS_DIR.iterdir()):
        if not area_dir.is_dir():
            continue
        for p in sorted(area_dir.rglob('*.json')):
            data = load(p)
            data['area'] = area_dir.name
            ancestor = p.parent.parent
            parent_id = None
            tier = 1
            while ancestor != area_dir and ancestor != ancestor.parent:
                bid = board_id_in_dir(ancestor)
                if bid and bid != data.get('id'):
                    if parent_id is None:
                        parent_id = bid
                    tier += 1
                ancestor = ancestor.parent
            data['parentBoardId'] = parent_id
            data['tier'] = tier
            data['isSubBoard'] = tier >= 2
            data['isTertiaryBoard'] = tier >= 3
            data['isQuaternaryBoard'] = tier >= 4
            data['isQuinaryBoard'] = tier >= 5
            if tier == 1 and area_dir.name == 'Legends' and data.get('name'):
                name = data['name']
                if name.lower() in LEGENDS_ORDER_LOWER:
                    data['sortOrder'] = (LEGENDS_ORDER_LOWER[name.lower()] + 1) * 10
            save(p, data)
    print('Fixed all board parents and tiers')

def gather():
    boards = []
    for area_dir in sorted(BOARDS_DIR.iterdir()):
        if not area_dir.is_dir():
            continue
        area = area_dir.name
        for p in sorted(area_dir.rglob('*.json')):
            data = load(p)
            boards.append((area, str(p.relative_to(BOARDS_DIR)), data))
    area_order = {'Common': 0, 'Legends': 1, 'Recipes': 2, 'Subject Vocab': 3, 'Sign': 4, 'My School': 5, 'Personal': 6}
    boards.sort(key=lambda t: (area_order.get(t[0], 99), t[1]))
    return boards

def esc(s):
    return s.replace("'", "\\'")

def rebuild_hierarchy():
    with open(HIERARCHY_BAK, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    start_line = end_line = None
    for i, line in enumerate(lines):
        if start_line is None and 'const List<BoardHierarchyEntry> boardHierarchy = [' in line:
            start_line = i
        elif start_line is not None and end_line is None and line.strip() == '];':
            end_line = i
            break
    boards = gather()
    id_to_name = {b[2]['id']: b[2]['name'] for b in boards}
    out_lines = []
    current = None
    for area, rel, data in boards:
        name = data.get('name', 'Board')
        pid = data.get('parentBoardId')
        pname = id_to_name.get(pid) if pid else None
        if current != area:
            if current is not None:
                out_lines.append('')
            out_lines.append(f"  // {'─' * 46}")
            out_lines.append(f"  //  {area.upper()} AREA")
            out_lines.append(f"  // {'─' * 46}")
            current = area
        if pname:
            out_lines.append(f"  BoardHierarchyEntry('{esc(name)}', '{esc(area)}', '{esc(pname)}'),")
        else:
            out_lines.append(f"  BoardHierarchyEntry('{esc(name)}', '{esc(area)}'),")
    out = lines[:start_line + 1] + ['\n'.join(out_lines) + '\n'] + lines[end_line:]
    with open(HIERARCHY_OUT, 'w', encoding='utf-8') as f:
        f.writelines(out)
    print(f'Rebuilt {HIERARCHY_OUT}')

def rebuild_index():
    boards = gather()
    with open(INDEX_OUT, 'w', encoding='utf-8') as f:
        f.write('// AUTO-GENERATED by tools/generate_board_index.py - do not edit manually.\n\n')
        f.write('class BoardIndexEntry {\n')
        f.write('  final String id;\n')
        f.write('  final String name;\n')
        f.write('  final String area;\n')
        f.write('  final String? parentBoardId;\n')
        f.write('  final bool isSubBoard;\n')
        f.write('  final bool isTertiaryBoard;\n')
        f.write('  final bool isQuaternaryBoard;\n')
        f.write('  final bool isQuinaryBoard;\n')
        f.write('  final int sortOrder;\n')
        f.write('  final int tier;\n')
        f.write('  final String? iconAssetPath;\n\n')
        f.write('  const BoardIndexEntry({\n')
        f.write('    required this.id,\n')
        f.write('    required this.name,\n')
        f.write('    required this.area,\n')
        f.write('    this.parentBoardId,\n')
        f.write('    this.isSubBoard = false,\n')
        f.write('    this.isTertiaryBoard = false,\n')
        f.write('    this.isQuaternaryBoard = false,\n')
        f.write('    this.isQuinaryBoard = false,\n')
        f.write('    this.sortOrder = 0,\n')
        f.write('    this.tier = 1,\n')
        f.write('    this.iconAssetPath,\n')
        f.write('  });\n')
        f.write('}\n\n')
        f.write('const List<BoardIndexEntry> staticBoardIndex = [\n')
        for area, rel, data in boards:
            name = data.get('name', 'Board').replace("'", "\\'")
            f.write('  BoardIndexEntry(\n')
            f.write(f"    id: '{data.get('id', '')}',\n")
            f.write(f"    name: '{name}',\n")
            f.write(f"    area: '{data.get('area', 'Common')}',\n")
            if data.get('parentBoardId'):
                f.write(f"    parentBoardId: '{data['parentBoardId']}',\n")
            f.write(f"    isSubBoard: {'true' if data.get('isSubBoard') else 'false'},\n")
            f.write(f"    isTertiaryBoard: {'true' if data.get('isTertiaryBoard') else 'false'},\n")
            f.write(f"    isQuaternaryBoard: {'true' if data.get('isQuaternaryBoard') else 'false'},\n")
            f.write(f"    isQuinaryBoard: {'true' if data.get('isQuinaryBoard') else 'false'},\n")
            f.write(f"    sortOrder: {data.get('sortOrder', 0)},\n")
            f.write(f"    tier: {data.get('tier', 1)},\n")
            if data.get('iconAssetPath'):
                f.write(f"    iconAssetPath: '{data['iconAssetPath']}',\n")
            f.write('  ),\n')
        f.write('];\n')
    print(f'Regenerated {INDEX_OUT} ({len(boards)} entries)')

def update_pubspec():
    with open(PUBSPEC, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    assets_start = assets_end = None
    for i, line in enumerate(lines):
        if assets_start is None and line.strip() == 'assets:':
            assets_start = i
        elif assets_start is not None:
            if line.strip() and not line.startswith(' ') and not line.startswith('\t'):
                assets_end = i
                break
    if assets_end is None:
        assets_end = len(lines)
    keep = []
    for line in lines[assets_start + 1:assets_end]:
        if re.search(r"lib/data/boards/", line):
            continue
        keep.append(line)
    entries = []
    for area_dir in sorted(BOARDS_DIR.iterdir()):
        if not area_dir.is_dir():
            continue
        entries.append(f"    - lib/data/boards/{area_dir.name}/\n")
        for sub in sorted(area_dir.rglob('*')):
            if sub.is_dir():
                rel = sub.relative_to(ROOT)
                entries.append(f"    - {rel.as_posix()}/\n")
    out = lines[:assets_start + 1] + keep + entries + lines[assets_end:]
    with open(PUBSPEC, 'w', encoding='utf-8') as f:
        f.writelines(out)
    print(f'Updated {PUBSPEC}')

def main():
    fix_all()
    rebuild_hierarchy()
    rebuild_index()
    update_pubspec()

if __name__ == '__main__':
    main()
