import os
import json

project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
boards_dir = os.path.join(project_root, 'lib', 'data', 'boards')

if not os.path.exists(boards_dir):
    print(f"Error: Boards directory not found at {boards_dir}")
    exit(1)

board_index = []

for root, dirs, files in os.walk(boards_dir):
    for file in files:
        if file.endswith('.json'):
            file_path = os.path.join(root, file)
            try:
                with open(file_path, 'r', encoding='utf-8-sig') as f:
                    data = json.load(f)
                    board_index.append({
                        'id': data.get('id', ''),
                        'name': data.get('name', 'Board'),
                        'area': data.get('area', 'Common'),
                        'parentBoardId': data.get('parentBoardId'),
                        'isSubBoard': data.get('isSubBoard', False),
                        'isTertiaryBoard': data.get('isTertiaryBoard', False),
                        'sortOrder': data.get('sortOrder', 0),
                        'tier': data.get('tier', 1),
                        'iconAssetPath': data.get('iconAssetPath'),
                    })
            except Exception as e:
                print(f"Error processing {file_path}: {e}")

output_path = os.path.join(project_root, 'lib', 'data', 'board_index.dart')

with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by tools/generate_board_index.py - do not edit manually.\n\n')
    f.write('class BoardIndexEntry {\n')
    f.write('  final String id;\n')
    f.write('  final String name;\n')
    f.write('  final String area;\n')
    f.write('  final String? parentBoardId;\n')
    f.write('  final bool isSubBoard;\n')
    f.write('  final bool isTertiaryBoard;\n')
    f.write('  final int sortOrder;\n')
    f.write('  final int tier;\n')
    f.write('  final String? iconAssetPath;\n\n')
    f.write('  const BoardIndexEntry({\n')
    f.write('    required this.id,\n')
    f.write('    required this.name,\n')
    f.write('    required this.area,\n')
    f.write('    this.parentBoardId,\n')
    f.write('    this.isSubBoard = False,\n')
    f.write('    this.isTertiaryBoard = False,\n')
    f.write('    this.sortOrder = 0,\n')
    f.write('    this.tier = 1,\n')
    f.write('    this.iconAssetPath,\n')
    f.write('  });\n')
    f.write('}\n\n')
    f.write('const List<BoardIndexEntry> staticBoardIndex = [\n')

    for entry in board_index:
        name_escaped = entry['name'].replace("'", "\\'")
        f.write('  BoardIndexEntry(\n')
        f.write(f"    id: '{entry['id']}',\n")
        f.write(f"    name: '{name_escaped}',\n")
        f.write(f"    area: '{entry['area']}',\n")
        if entry['parentBoardId']:
            f.write(f"    parentBoardId: '{entry['parentBoardId']}',\n")
        f.write(f"    isSubBoard: {'true' if entry['isSubBoard'] else 'false'},\n")
        f.write(f"    isTertiaryBoard: {'true' if entry['isTertiaryBoard'] else 'false'},\n")
        f.write(f"    sortOrder: {entry['sortOrder']},\n")
        f.write(f"    tier: {entry['tier']},\n")
        if entry['iconAssetPath']:
            f.write(f"    iconAssetPath: '{entry['iconAssetPath']}',\n")
        f.write('  ),\n')

    f.write('];\n')

print(f"Board index generated with {len(board_index)} entries at {output_path}")
