import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;

void main() async {
  final projectRoot = p.dirname(p.dirname(Platform.script.toFilePath()));
  final boardsDir = Directory(p.join(projectRoot, 'lib', 'data', 'boards'));
  
  if (!await boardsDir.exists()) {
    print('Error: Boards directory not found at ${boardsDir.path}');
    return;
  }

  final index = <Map<String, dynamic>>[];
  
  final entities = boardsDir.listSync(recursive: true);
  for (final entity in entities) {
    if (entity is File && entity.path.endsWith('.json')) {
      try {
        final content = await entity.readAsString();
        final data = json.decode(content) as Map<String, dynamic>;
        
        index.add({
          'id': data['id'],
          'name': data['name'],
          'area': data['area'] ?? 'Common',
          'parentBoardId': data['parentBoardId'],
          'isSubBoard': data['isSubBoard'] ?? false,
          'isTertiaryBoard': data['isTertiaryBoard'] ?? false,
          'sortOrder': data['sortOrder'] ?? 0,
          'tier': data['tier'] ?? 1,
          'iconAssetPath': data['iconAssetPath'],
        });
      } catch (e) {
        print('Error processing ${entity.path}: $e');
      }
    }
  }

  final buffer = StringBuffer();
  buffer.writeln('// AUTO-GENERATED by tools/generate_board_index.dart - do not edit manually.');
  buffer.writeln('');
  buffer.writeln('class BoardIndexEntry {');
  buffer.writeln('  final String id;');
  buffer.writeln('  final String name;');
  buffer.writeln('  final String area;');
  buffer.writeln('  final String? parentBoardId;');
  buffer.writeln('  final bool isSubBoard;');
  buffer.writeln('  final bool isTertiaryBoard;');
  buffer.writeln('  final int sortOrder;');
  buffer.writeln('  final int tier;');
  buffer.writeln('  final String? iconAssetPath;');
  buffer.writeln('');
  buffer.writeln('  const BoardIndexEntry({');
  buffer.writeln('    required this.id,');
  buffer.writeln('    required this.name,');
  buffer.writeln('    required this.area,');
  buffer.writeln('    this.parentBoardId,');
  buffer.writeln('    this.isSubBoard = false,');
  buffer.writeln('    this.isTertiaryBoard = false,');
  buffer.writeln('    this.sortOrder = 0,');
  buffer.writeln('    this.tier = 1,');
  buffer.writeln('    this.iconAssetPath,');
  buffer.writeln('  });');
  buffer.writeln('}');
  buffer.writeln('');
  buffer.writeln('const List<BoardIndexEntry> staticBoardIndex = [');
  
  for (final entry in index) {
    buffer.writeln('  BoardIndexEntry(');
    buffer.writeln('    id: \'${entry['id']}\',');
    buffer.writeln('    name: \'${entry['name'].toString().replaceAll("'", "\\'")}\',');
    buffer.writeln('    area: \'${entry['area']}\',');
    if (entry['parentBoardId'] != null) buffer.writeln('    parentBoardId: \'${entry['parentBoardId']}\',');
    buffer.writeln('    isSubBoard: ${entry['isSubBoard']},');
    buffer.writeln('    isTertiaryBoard: ${entry['isTertiaryBoard']},');
    buffer.writeln('    sortOrder: ${entry['sortOrder']},');
    buffer.writeln('    tier: ${entry['tier']},');
    if (entry['iconAssetPath'] != null) buffer.writeln('    iconAssetPath: \'${entry['iconAssetPath']}\',');
    buffer.writeln('  ),');
  }
  
  buffer.writeln('];');

  final outputFile = File(p.join(projectRoot, 'lib', 'data', 'board_index.dart'));
  await outputFile.writeAsString(buffer.toString());
  print('Board index generated with ${index.length} entries at ${outputFile.path}');
}
