"""Scan assets/ for all .png files and generate lib/data/symbol_data.dart"""
import os
import re
from pathlib import Path

PROJECT = Path(r"C:\Users\Craig\Downloads\Charlie Chat")
ASSETS_DIR = PROJECT / "assets"
OUTPUT = PROJECT / "lib" / "data" / "symbol_data.dart"

CATEGORIES_ORDER = [
    "Actions", "Adjectives", "Adverbs", "Alphabet",
    "Animals & Habitats", "Body Parts", "Careers",
    "Classroom Equipment", "Clothes", "Colours",
    "Common", "Common Interests", "Feelings & Emotions",
    "More", "Movement", "Nouns", "People", "Places",
    "Prepositions", "Time", "Toys", "Vehicles",
    "Verbs", "Weather",
]

tiles = []
categories_found = set()

for png in sorted(ASSETS_DIR.rglob("*.png")):
    cat_name = png.parent.name
    categories_found.add(cat_name)
    stem = png.stem
    label = stem.replace("_", " ").replace("-", " ").title()
    for word in ["And", "Of", "The", "A", "An"]:
        label = label.replace(f" {word} ", f" {word.lower()} ")
    rel_path = png.relative_to(PROJECT)
    asset_path = str(rel_path).replace("\\", "/")
    safe_id = f"sym_{cat_name.lower().replace(' ', '_').replace('&', 'and')}_{stem.lower().replace(' ', '_').replace('-', '_')}"
    safe_id = re.sub(r'[^a-z0-9_]', '', safe_id)
    tiles.append((safe_id, label, cat_name, asset_path))

# Sort categories: known order first, then alphabetical for any extras
ordered = [c for c in CATEGORIES_ORDER if c in categories_found]
extras = sorted(categories_found - set(CATEGORIES_ORDER))
all_cats = ordered + extras

lines = []
lines.append("// AUTO-GENERATED by tools/generate_symbol_data.py - do not edit manually.")
lines.append("// Scans assets/ for all .png files.")
lines.append("")
lines.append("import '../models/symbol_tile.dart';")
lines.append("")
lines.append("final List<String> allCategories = [")
lines.append("  'All',")
for cat in all_cats:
    lines.append(f"  '{cat}',")
lines.append("];")
lines.append("")
lines.append("final List<SymbolTile> allSymbolTiles = [")
for sid, label, cat, asset in tiles:
    # Escape apostrophes and $ for Dart single-quoted strings
    sid_e = sid.replace("'", "\\'").replace("$", "\\$")
    label_e = label.replace("'", "\\'").replace("$", "\\$")
    cat_e = cat.replace("'", "\\'").replace("$", "\\$")
    asset_e = asset.replace("'", "\\'").replace("$", "\\$")
    lines.append(f"  SymbolTile(id: '{sid_e}', label: '{label_e}', category: '{cat_e}', imageAsset: '{asset_e}'),")
lines.append("];")

OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {len(tiles)} tiles across {len(all_cats)} categories to {OUTPUT}")
